mysite/dl_manage/urls.py
from django.conf.urls import url
from . import views

app_name = "dl_manage"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add/$', views.add, name="add"),
    url(r'^save/$', views.save, name="save"),
    url(r'^delete/$', views.delete, name="delete"),
    url(r'^loadmodels/$', views.loadmodels, name="loadmodels"),
    url(r'^fillmodel/$', views.fillmodel, name="fillmodel"),
    url(r'^id/(?P<model_id>[0-9]+)/data/(?P<inputStr>.+)$', views.predict, name="predict"),
    url(r'^plot/(?P<model_id>[0-9]+)$', views.plot, name="plot"),
    url(r'^stop/(?P<model_id>[0-9]+)$', views.stop, name="stop"),
    url(r'^invoke/$', views.invoke, name="invoke")
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [	
    url(r'^manage/', include('dl_manage.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/dl_manage/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models


# Create your models here.


class Category(models.Model):
    type_1 = models.CharField(max_length=30)
    type_2 = models.CharField(max_length=30)

    def __str__(self):
        return self.type_1 + "." + self.type_2


class Data(models.Model):
    data_file = models.FileField(upload_to="data/")
    dimension_in = models.IntegerField()
    dimension_out = models.IntegerField()

    def __str__(self):
        return str(self.data_file)


class LearningModel(models.Model):
    model_name = models.CharField(max_length=50)
    type = models.ForeignKey(Category, on_delete=models.CASCADE)
    data = models.ForeignKey(Data, null=True, on_delete=models.SET_NULL)
    dimension_in = models.IntegerField()
    dimension_out = models.IntegerField()
    data_name = models.CharField(max_length=255)
    num_layer = models.IntegerField(default=2)
    num_unit = models.CharField(max_length=255)
    lr = models.FloatField()
    num_iter = models.IntegerField()
    num_batch = models.IntegerField()
    arg_params = models.BinaryField(null=True)
    aux_params = models.BinaryField(null=True)
    symbol = models.TextField(null=True)
    norm_para = models.BinaryField(null=True)
    train_error = models.FloatField(null=True)
    test_error = models.FloatField(null=True)
    time = models.FloatField(default=0.0)
    comment = models.TextField(blank=True)


    def get_intro(self):
        return u"模型ID：%s\n模型名称：%s\n一级分类：%s\n二级分类：%s\n特征个数：%s\n结果个数：%s\n网络层数：%s\n各层神经元个数：%s\n" \
               u"学习率：%s\n迭代次数：%s\nBatch：%s\n训练时间：%s\n训练误差：%s\n测试误差：%s\n备注：\n%s\n" \
               % (self.id, self.model_name, self.type.type_1, self.type.type_2, self.dimension_in, self.dimension_out,
                  self.num_layer, self.num_unit, self.lr, self.num_iter, self.num_batch, self.time, self.train_error, self.test_error, self.comment)


    def __str__(self):
        return str(self.type) + "." + self.model_name

mysite/dl_manage/views.py
# -*- coding: utf-8 -*-

from collections import deque
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from models import Category, Data, LearningModel
from subprocess import call, Popen
import os
import datetime
import json
import urllib2
import pickle
import numpy as np
import mxnet as mx


# Create your views here.

count = {}
count_list = {}
sub_process = {}
LearningModel_set = list()

def index(request):
    if request.is_ajax():
        type1 = request.GET["type1"]
        type2_set = [category.type_2 for category in
                     Category.objects.filter(type_1=type1).order_by("type_2")]
        return JsonResponse(type2_set, safe=False)

    if "add_type" in request.POST:
        type1 = request.POST["newType1"]
        type2 = request.POST["newType2"]
        category = Category(type_1=type1, type_2=type2)
        category.save()

    type1_set = [category["type_1"] for category in Category.objects.all().values("type_1").distinct().order_by("type_1")]
    type_set = [(type1, [category for category in Category.objects.filter(type_1=type1).order_by("type_2")])
                for type1 in type1_set]

    with open('dl_manage/topic_config.json') as data_file:
        data = json.load(data_file)
        sub_topic_set = data['topic_sub']
        pub_topic_set = data['topic_pub']
    return render(request, "dl_manage/index.html", {"type_set": type_set, "data_set": Data.objects.all(), "sub_topic_set": sub_topic_set, "pub_topic_set": pub_topic_set})


def add(request):
    model_id = request.POST["model_id"]
    type1 = request.POST["typeSel1"]
    type2 = request.POST["typeSel2"]
    category = Category.objects.get(type_1=type1, type_2=type2)
    model_name = request.POST["model_name"]
    num_network = int(request.POST["num_network"])
    net_set = [(request.POST["num_layer" + str(i + 1)],
                request.POST["num_unit" + str(i + 1)]) for i in xrange(num_network)]
    max_iter = request.POST["max_iter"]
    loss = request.POST["loss"]
    # learning rate
    if request.POST["lrRadio"] == "lr1":
        lr_set = [request.POST["lr"]]
    else:
        begin = float(request.POST["lr-begin"])
        end = float(request.POST["lr-end"])
        step = float(request.POST["lr-step"])
        num = int((end - begin) / step)
        lr_set = [begin + i * step for i in xrange(num + 1)]
    # number of a batch
    if request.POST["batchRadio"] == "batch1":
        num_batch_set = [request.POST["num_batch"]]
    else:
        begin = float(request.POST["batch-begin"])
        end = float(request.POST["batch-end"])
        step = float(request.POST["batch-step"])
        num = int((end - begin) / step)
        num_batch_set = [begin + i * step for i in xrange(num + 1)]

    d_in = request.POST["d_in"]
    d_out = request.POST["d_out"]
    comment = request.POST["comment"]
    if request.POST["fileRadio"] == "file1":
        data = Data.objects.get(id=request.POST["file_data"])
    else:
        file_data = request.FILES["file_data"]
        data = Data(data_file=file_data, dimension_in=d_in, dimension_out=d_out)
        data.save()

    norm_para = preProcess(data)

    global LearningModel_set
    LearningModel_set = []
    if model_id != "0":
        lmodel = LearningModel.objects.get(id=model_id)
        lmodel.model_name = model_name
        lmodel.type = category
        if lmodel.num_layer == int(net_set[0][0]) and lmodel.num_unit == net_set[0][1] \
                and lmodel.num_iter == int(max_iter) and lmodel.num_batch == int(num_batch_set[0]) \
                and lmodel.lr == float(lr_set[0]) and  lmodel.error_rate == float(loss) and lmodel.data.id == data.id:
            lmodel.save()
            return HttpResponseRedirect(reverse('dl_manage:index'))
        lmodel.data = data
        lmodel.num_layer, lmodel.num_unit = net_set[0]
        lmodel.lr = lr_set[0]
        lmodel.num_batch = num_batch_set[0]
        lmodel.comment = comment
        train(lmodel, loss, max_iter)
        LearningModel_set.append(lmodel)
    else:
        i = 1
        for num_layer, num_unit in net_set:
            for lr in lr_set:
                for num_batch in num_batch_set:
                    if i == 1:
                        name = model_name
                    else:
                        name = "%s (%d)" % (model_name, i)

                    lmodel = LearningModel(model_name=name, type=category, data=data, dimension_in=d_in, dimension_out=d_out, num_layer=num_layer, num_unit=num_unit,
                                           data_name=data.data_file.name, lr=lr, num_batch=num_batch, norm_para= norm_para, comment=comment)
                    train(lmodel, max_iter, loss)
                    LearningModel_set.append(lmodel)
                    i += 1
    data_path = data.data_file.name
    data_name = data_path[data_path.find('/')+1:data_path.rfind('.')]
    os.remove('data/'+data_name+'_train_data.csv')
    os.remove('data/'+data_name+'_train_label.csv')
    os.remove('data/'+data_name+'_test_data.csv')
    os.remove('data/'+data_name+'_test_label.csv')
    LearningModel_set.sort(key=lambda lmodel: lmodel.train_error)
    return render(request, "dl_manage/add.html", {"lmodel_set": LearningModel_set})


def save(request):
    global LearningModel_set
    if "model" in request.POST:
        index = request.POST.getlist("model")
        for i in index:
            LearningModel_set[int(i)].save()
    return HttpResponseRedirect(reverse('dl_manage:index'))


def delete(request):
    if request.GET["type"] == "model":
        model_id = request.GET["id"]
        lmodel = LearningModel.objects.get(id=model_id)
        result = lmodel.delete()
    elif request.GET["type"] == "data":
        data_id = request.GET["id"]
        data = Data.objects.get(id=data_id)
        data.data_file.delete()
        result = data.delete()
    return HttpResponse(result[0])


def loadmodels(request):
    type_id = request.GET["type_id"]
    lmodel_set = LearningModel.objects.filter(type__id=type_id).order_by("model_name")
    model_set = [{"id": lmodel.id, "name": lmodel.model_name} for lmodel in lmodel_set]
    return JsonResponse(model_set, safe=False)


def fillmodel(request):
    model_id = request.GET["model_id"]
    lmodel = LearningModel.objects.get(id=model_id)
    model_dict = dict()
    model_dict["id"] = lmodel.id
    model_dict["model_name"] = lmodel.model_name
    if request.GET["query_type"] == "lite":
        model_dict["intro"] = lmodel.get_intro()
    elif request.GET["query_type"] == "full":
        model_dict["type1"] = lmodel.type.type_1
        model_dict["type2"] = lmodel.type.type_2
        model_dict["num_layer"] = lmodel.num_layer
        model_dict["num_unit"] = lmodel.num_unit
        model_dict["lr"] = lmodel.lr
        model_dict["loss"] = lmodel.error_rate
        model_dict["num_iter"] = lmodel.num_iter
        model_dict["num_batch"] = lmodel.num_batch
        model_dict["d_in"] = lmodel.dimension_in
        model_dict["d_out"] = lmodel.dimension_out
        if lmodel.data:
            model_dict["file"] = lmodel.data.id
        else:
            model_dict["file"] = ""
        model_dict["comment"] = lmodel.comment
    return JsonResponse(model_dict)

def preProcess(data):
    data_path = data.data_file.name
    data_name = data_path[data_path.find('/')+1:data_path.rfind('.')]
    d_in = int(data.dimension_in)
    data = np.loadtxt(data_path)
    np.random.shuffle(data)
    num = data.shape[0]
    tmp = data[:,:d_in]
    minVals = tmp.min(0)
    maxVals = tmp.max(0)
    ranges = maxVals-minVals
    k = 0
    for each in ranges:
        if each == 0:
            ranges[k] = 1
        k = k + 1
    norm = tmp-np.tile(minVals,(num,1))
    norm = norm/np.tile(ranges,(num,1))
    norm_para = np.vstack((minVals,ranges))
    labels = data[:,d_in:]
    trainData = norm[0:num*3/4+1].tolist()
    trainLabel = labels[0:num*3/4+1].tolist()
    testData = norm[num*3/4+1:].tolist()
    testLabel = labels[num*3/4+1:].tolist()
    np.savetxt('data/'+data_name+'_train_data.csv', trainData, delimiter=",")
    np.savetxt('data/'+data_name+'_train_label.csv', trainLabel, delimiter=",")
    np.savetxt('data/'+data_name+'_test_data.csv', testData, delimiter=",")
    np.savetxt('data/'+data_name+'_test_label.csv', testLabel, delimiter=",")
    return pickle.dumps(norm_para)

def train(lmodel, max_iter, loss):
    data_path = lmodel.data.data_file.name
    data_name = data_path[data_path.find('/')+1:data_path.rfind('.')]
    num_unit_tmp = str(lmodel.num_unit).split()
    num_unit = ''
    for each in num_unit_tmp:
        num_unit = num_unit + each + ' '
    num_unit = num_unit.strip().replace(' ','k')
    starttime = datetime.datetime.now()
    call(["python train.py --kv-store local"+\
    " --data-name "+str(data_name)+" --d-in "+str(lmodel.dimension_in)+" --d-out "+ str(lmodel.dimension_out)+" --"+\
    "num-layer "+str(lmodel.num_layer)+" --num-unit "+str(num_unit)+" --lr "+str(lmodel.lr)+" --batch-size "+str(lmodel.num_batch)+" --"+\
    "num-epochs "+str(max_iter)+" --loss "+str(loss)], shell = True)
    endtime = datetime.datetime.now()
    lmodel.time = (endtime - starttime).seconds
    with open('tmp_result1.json') as file:
        tmp_result = json.load(file)
        lmodel.num_iter = tmp_result['num_iter']
        lmodel.train_error = tmp_result['train_error']
        lmodel.test_error = tmp_result['test_error']
        lmodel.symbol = tmp_result['symbol']
    with open('tmp_result2.txt', mode='rb') as file:
        lmodel.arg_params = file.read()
    with open('tmp_result3.txt', mode='rb') as file:
        lmodel.aux_params = file.read()
    if os.path.isfile('tmp_result1.json'):
        os.remove('tmp_result1.json')
    if os.path.isfile('tmp_result2.txt'):
        os.remove('tmp_result2.txt')
    if os.path.isfile('tmp_result3.txt'):
        os.remove('tmp_result3.txt')

mysite/dl_manage/templates/dl_manage/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>机器学习管理系统</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/me.css' %}" rel="stylesheet">
  </head>

  <body>
    <div class="header">
      <div class="container"><h1>机器学习管理系统</h1></div>
    </div>
    
    <div class="container">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#Part1" aria-controls="Part1" role="tab" data-toggle="tab">添加新模型</a>
      </li>
      <li role="presentation">
        <a href="#Part2" aria-controls="Part2" role="tab" data-toggle="tab">模型管理</a>
      </li>
    </ul>
    </div>

    <div class="container">
    <div id="myTabContent" class="tab-content">
      <!-- Tab 1 -->
      <div role="tabpanel" class="tab-pane active" id="Part1">        
        <form action="{% url 'dl_manage:add' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="model_id" id="model_id" value="0">
          <div class="form-group">
            <label for="typeSel1">一级分类</label>
            <label for="typeSel1" class="control-label"></label>
            <select id="typeSel1" name="typeSel1" class="form-control required">
              <option value=""></option>
              {% for type in type_set %}
                <option value="{{ type.0 }}">{{ type.0 }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label for="typeSel2">二级分类</label>
            <label for="typeSel1" class="control-label"></label>
            <select id="typeSel2" name="typeSel2" class="form-control required">
              <option value=""></option>
            </select>
          </div>
          <div class="form-group">
            <label for="model_name">模型名称</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="model_name" name="model_name" class="form-control required">
          </div>
          <div class="form-group">
            <label for="num_layer">网络层数</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="num_layer" name="num_layer" class="form-control required number">
          </div>
          <div class="form-group">
            <label for="num_unit">每层神经元个数（用空格分隔）</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="num_unit" name="num_unit" class="form-control required numlist">
          </div>
          <div class="form-group">
            <label for="lr">学习率</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="lr" name="lr" class="form-control required number">
          </div>
          <div class="form-group">
            <label for="d_in">特征个数</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="d_in" name="d_in" class="form-control required number">
          </div>
          <div class="form-group">
            <label for="d_out">结果个数</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="text" id="d_out" name="d_out" class="form-control required number">
          </div>
          <div class="form-group">
            <label for="file_data">数据文件</label>
            <label for="typeSel1" class="control-label"></label>
            <input type="file" id="file_data" name="file_data" class="form-control">
          </div>
          <div class="form-group">
            <label for="comment">备注</label>
            <textarea class="form-control" id="comment" name="comment" rows="5"></textarea>
          </div>
          <span style="margin-right:20px">
          <input type="submit" name="add" value="提交" class="btn btn-primary">
          </span>
          <span style="margin-right:20px">
          <input type="reset" value="重置" class="btn btn-primary">
          </span>
        </form><br />
      </div>  <!-- Tab 1 -->
      <!-- Tab 2 -->
      <div role="tabpanel" class="tab-pane" id="Part2">        
        <div class="row">
          <div class="col-md-3">
          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            {% for type1, type2_set in type_set %}
            <div class="panel panel-primary">
              <div class="panel-heading" role="tab">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse" data-parent="#accordion" href="#type1_{{ type2_set.0.id }}"
                     aria-expanded="true" aria-controls="type1_{{ type2_set.0.id }}">{{ type1 }}</a>
                </h4>
              </div>

              <div id="type1_{{ type2_set.0.id }}" class="panel-collapse collapse" role="tabpanel">
                <div class="panel-body">
                  <div class="panel-group" id="accordion_{{ type2_set.0.id }}" role="tablist" aria-multiselectable="true">
                  {% for type2 in type2_set %}
                  <div class="panel panel-info">
                    <div class="panel-heading" role="tab">
                      <h4 class="panel-title">
                        <a role="button" class="loadmodels" data-toggle="collapse" data-parent="#accordion_{{ type2_set.0.id }}" data-id="{{ type2.id }}" href="#type2_{{ type2.id }}" aria-expanded="true" aria-controls=" type2_{{ type2.id }}">{{ type2.type_2 }}</a>
                      </h4>
                    </div>

                    <div id="type2_{{ type2.id }}" class="panel-collapse collapse" role="tabpanel">
                      <div class="panel-body"></div>
                    </div>
                  </div>
                  {% endfor %}
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          </div>

          <div class="col-md-9">
          <form id="" action="{% url 'dl_manage:delete' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="mId" id="mId" value="0">
            <div class="form-group">
              <label for="mName">模型名称</label>
              <input type="text" class="form-control" name="mName" id="mName" disabled>
            </div>
            <div class="form-group">
              <label for="mIntro">模型简述</label>
              <textarea class="form-control" rows="10" name="mIntro" id="mIntro" disabled></textarea>
            </div>
            <div class="form-group">
              <label for="data">数据</label>
              <label class="radio-inline">
                <input type="radio" name="dataRadio" id="dataType1" value="data1" checked>输入数据
              </label>
              <label class="radio-inline">
                <input type="radio" name="dataRadio" id="dataType2" value="data2">数据文件
              </label>
              <input type="text" class="form-control" id="data">
            </div>
            <span style="margin-right:20px">
            <button type="button" class="btn btn-primary" id="invoke">调用</button>
            </span>
            <span style="margin-right:20px">
            <button type="button" class="btn btn-primary" id="modify">修改</button>
            </span>
            <button type="submit" class="btn btn-primary" id="delete">删除</button>
          </form><br />
          </div>
        </div>
      </div>  <!-- Tab 2 -->
    </div>  <!-- tab-content -->
    </div>  <!-- container -->

    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/me.js' %}"></script>
  </body>
</html>

mysite/dl_manage/templates/dl_manage/notification.html
<script type="text/javascript">
	var type = "{{ type }}";
	switch(type){
		case "delete":
			alert("删除成功！");
			window.location.href = "{% url 'dl_manage:index' %}";
			
			break;
		case "add":
			alert("添加成功！");
			window.location.href = "{% url 'dl_manage:index' %}";
			break;
	}
</script>